In [16]:
import kagglehub
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import os

import torch.nn as nn
import torch
from torch.utils.data import Dataset, DataLoader
import torchtext
from torchtext.data.utils import get_tokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
)
from torchtext.vocab import Vocab
from collections import Counter

from kagglehub import KaggleDatasetAdapter
    
warnings.filterwarnings("ignore")

# # !pip3 install torch==2.3.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
# # # !pip uninstall torch torchvision torchaudio -y


In [17]:
lstm = nn.LSTM(3,3) #input dimension is 3 and output is 3



# torch.randn(1, 3) generates a 1x3 tensor (1 row, 3 columns) with 
# values sampled from a standard normal distribution (mean = 0, standard deviation = 1).

inputs = [torch.randn(1,3) for _ in range(5)]

print(inputs)


[tensor([[ 0.7483, -1.2564, -0.1777]]), tensor([[-0.8497, -0.6588, -0.6634]]), tensor([[-0.0819,  0.5312, -0.5368]]), tensor([[-0.3703, -0.1243, -0.6266]]), tensor([[-0.5575, -1.0728,  2.9771]])]


In [18]:
# print(torch.randn(1,1,3))
# print(torch.randn(1,1,2))
# print(torch.randn(1,1))

# torch.randn(1, 1, 3) generates three dimensional tensor shape 

hidden = (torch.randn(1,1,3),torch.randn(1,1,3))

print(hidden)

print()

for i in inputs:
    out, hidden = lstm(i.view(1,1, -1), hidden)
    print("out", out)
    print("hidden", hidden)



(tensor([[[ 1.3134, -2.2887,  2.1301]]]), tensor([[[ 0.9534, -0.7266,  0.2278]]]))

out tensor([[[ 0.2829, -0.5359, -0.1180]]], grad_fn=<StackBackward0>)
hidden (tensor([[[ 0.2829, -0.5359, -0.1180]]], grad_fn=<StackBackward0>), tensor([[[ 0.6394, -0.7546, -0.1456]]], grad_fn=<StackBackward0>))
out tensor([[[ 0.2052, -0.3773, -0.2537]]], grad_fn=<StackBackward0>)
hidden (tensor([[[ 0.2052, -0.3773, -0.2537]]], grad_fn=<StackBackward0>), tensor([[[ 0.4569, -0.5003, -0.4993]]], grad_fn=<StackBackward0>))
out tensor([[[ 0.2016, -0.4478, -0.3024]]], grad_fn=<StackBackward0>)
hidden (tensor([[[ 0.2016, -0.4478, -0.3024]]], grad_fn=<StackBackward0>), tensor([[[ 0.3549, -0.6389, -0.7307]]], grad_fn=<StackBackward0>))
out tensor([[[ 0.1443, -0.4259, -0.3556]]], grad_fn=<StackBackward0>)
hidden (tensor([[[ 0.1443, -0.4259, -0.3556]]], grad_fn=<StackBackward0>), tensor([[[ 0.2890, -0.5830, -0.8256]]], grad_fn=<StackBackward0>))
out tensor([[[-0.1439,  0.2282, -0.3347]]], grad_fn=<StackBackward0>

In [49]:

#Torch.cat(): Concatenates the given sequence of tensors in tensors in the given dimension

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a)
print()
print(b)

print(torch.cat((a, b), 0))
print()
print(torch.cat((a, b), 0))
print()




# inputs = torch.cat(inputs).view(len(inputs),1, -1) 
# print(inputs)

tensor([1, 2, 3])

tensor([4, 5, 6])
tensor([1, 2, 3, 4, 5, 6])

tensor([1, 2, 3, 4, 5, 6])

